# Generated by Django 2.0 on 2018-04-25 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0004_auto_20180425_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 11, 26, 47, 862241, tzinfo=utc)),
        ),
    ]
