# Generated by Django 2.0 on 2018-04-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0006_auto_20180425_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='file',
        ),
    ]
