# Generated by Django 2.0 on 2018-04-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0007_auto_20180425_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
